name: "check"
on:
  pull_request:
    branches: ["main"]

jobs:
  # diff:
  #   name: "Diff"
  #   uses: Ritik0306/my-first-tf-repo/.github/workflows/diff.yml@main
  #   with:
  #     config: diff-config.yaml
  #   secrets:
  #     GITHUB: ${{ secrets.GITHUB }}

  terraform:
    # needs: [diff]
    name: "Terraform"
    # if: ${{ fromJson(needs.diff.outputs.tags).terraform.changed }}
    uses: aravind15b/infra_repo1/.github/workflows/terraform-check.yml@main
    secrets:
      GITHUB: ${{ secrets.GITHUB }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

