name: Build
on:
  push:
    # On push to $default-branch
    branches: ['test/percona']

jobs:  
  terraform-apply:
    name: "Terraform apply"
    uses: Ritik0306/acs_java/.github/workflows/workflow-trigger.yaml@test/percona
    with:
      workflow: main
      ref: ${{ github.ref }}
      inputs: |
        env: ${{ vars.test }}
        ref: ${{ github.sha }}
    secrets:
      GITHUB: ${{ secrets.GITHUB }}