name: "check"
on:
  pull_request:
    branches: ["main"]

jobs:
  diff:
    runs-on: ubuntu-20.04
    outputs:
      terraform: ${{ steps.changes.outputs.terraform }}
      Java: ${{ steps.changes.outputs.Java }}

    steps:
    -
      id: checkout
      uses: actions/checkout@v1
    -
      id: changes
      run: |
        echo terraform=$(git diff --quiet HEAD ${{ github.event.pull_request.base.sha }} -- infra/terraform/ && echo unchanged || echo changed) >> $GITHUB_OUTPUT
        echo Java=$(git diff --quiet HEAD ${{ github.event.pull_request.base.sha }} -- src/ && echo unchanged || echo changed) >> $GITHUB_OUTPUT

  terraform:
    needs: [diff]
    name: "Terraform"
    # if: ${{ fromJson(needs.diff.outputs.tags).terraform.changed }}
    uses: aravind15b/infra_repo1/.github/workflows/terraform-check.yml@main
    secrets:
      GITHUB: ${{ secrets.GITHUB }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

