name: Build and Push
on:
  push:
jobs:
  Docker_build:
    name: test
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.bump_version.outputs.tag }}
    steps:
    - name: Bump release version
      id: bump_version
      run: echo "tag=$(echo ${GITHUB_RUN_NUMBER}-${GITHUB_SHA:0:3})" >> $GITHUB_OUTPUT
    - name: Build image
      run: echo ${{ steps.bump_version.outputs.tag }}
  Test:
    name: testing
    runs-on: ubuntu-latest
    needs: Docker_build
    steps:
      - name: echo
        run: echo ${{ needs.Docker_build.outputs.image_tag}}
