name: Build and Push
on:
  push:

jobs:
  Docker_build:
    name: Code checkout
    runs-on: ubuntu-latest
    services:
      percona:
        image: percona:5.6
        env:
          MYSQL_ROOT_PASSWORD: ci
        ports: 
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3 --name percona
    steps:
      - name: Get Container Name
        id: get-container-name
        run: |
          CONTAINER_NAME=$(docker ps --filter "label=com.github.actions.job=$GITHUB_JOB" --format "{{.Names}}")
          echo "Container Name: $CONTAINER_NAME"
