name: Build and Push
on:
  push:
jobs:
  Docker_build:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: Bump release version
      id: bump_version
      uses: christian-draeger/increment-semantic-version@1.1.0
      with:
        current-version: '1.0.0' # also accepted: 'v2.11.7-alpha.3' | '2.11.7-alpha3'
        version-fragment: 'feature'
    - name: Build image
      run: echo ${{ steps.bump_version.outputs.next-version }}
