name: Build and Push
on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Target environment'
        required: true
        type: choice
      ref:
        description: Git Ref (Default to workflow branch)
        required: false

jobs:
  Docker_build:
    name: Code checkout
    runs-on: ubuntu-latest
    steps:
      - name: Run Ubuntu container in the same network
        run: |
          echo ${{ github.event.inputs.env }} > test.txt
          cat test.txt
