name: Build
on:
  push:
    # On push to $default-branch
    # branches: ["main"]

jobs:
  # diff:
  #   name: "Diff"
  #   uses: achieve-3000/github-actions/.github/workflows/diff.yaml@v2
  #   with:
  #     config: diff-config.yaml
  #   secrets:
  #     CI_PAT: ${{ secrets.CI_PAT }}

  terraform-apply:
    # needs: [diff]
    name: "Terraform apply"
    # if: ${{ fromJson(needs.diff.outputs.tags).terraform.changed }}
    uses: aravind15b/infra_repo1/.github/workflows/workflow-trigger.yaml@main
    with:
      workflow: terraform-apply
      ref: ${{ github.ref }}
      inputs: |
        env: ${{ github.event.inputs.env }}
        ref: ${{ github.sha }}
    secrets:
      GITHUB: ${{ secrets.GITHUB }}
