name: main
on:
  push:
    branches: test/build_change

jobs:
  Build:
    name: "Build"
    uses: Ritik0306/acs_java/.github/workflows/build.yml@test/build_change
    secrets:
      GITHUB: ${{ secrets.GITHUB }}