name: Build and Push
on:
  push:
    branches:
      - feature/*
      - k8s-*
jobs:  
  test_migrations:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout Project
        run: echo "hello-world"
