name: Build and Push
on:
  push:
jobs:
  Docker_build:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Get next version
      uses: reecetech/version-increment@2023.9.3
      id: version
      with:
        scheme: semver
        increment: patch
    - name: Build image
      run: echo ${{ steps.version.outputs.version }}
