name: Build and Push
on:
  push:

jobs:
  Docker_build:
    name: Code checkout
    runs-on: ubuntu-latest
    steps:
      - name: Run Ubuntu container in the same network
        run: |
          echo ${{ vars.TEST }} > test.txt
          echo $test.txt
