name: Build and Push
on:
  push:

jobs:
  Docker_build:
    name: Code checkout
    runs-on: ["self-hosted", "core-qa"]
    services:
      mydb:
        image: percona:5.6
        env:
          MYSQL_ROOT_PASSWORD: ci
        ports: 
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Build and Push Image
        run: |
          sleep 120
          docker ps -a
          mysql -hmydb -uroot -pci
