name: Terraform apply
on:
  repository_dispatch:
    types: [terraform-apply]
  workflow_dispatch:
    inputs:
      env:
        description: 'Target environment'
        default: qa
        required: true
        type: choice
        options:
          - qa
          - dev
          - prod
      ref:
        description: Git Ref (Default to workflow branch)
        required: false

jobs:
  terraform:
    name: "Terraform"
    uses: Ritik0306/my-first-tf-repo/.github/workflows/apply.yaml@main
    with:
      ref: ${{ github.event.inputs.ref }}
      env: ${{ github.event.inputs.env }}
    secrets:
      GITHUB: ${{ secrets.GITHUB }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}